### ISSUE TITLE
Fail to start on Mac

### ISSUE THREAD

**Issue by j2l** [AppyBuilder/AppyBuilderPersonal#4]
JDK is 9.0.4 (using brew cask) but I get a "failure while recording an error" 🥇:
```
AppyBuilderPersonal pm$ sh ./startAIServer.sh 
SDK_BIN is: /Users/pm/Documents/GitHub/AppyBuilderPersonal/AppEngine
Executing [/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/bin/java, -XstartOnFirstThread, -javaagent:/Users/pm/Documents/GitHub/AppyBuilderPersonal/AppEngine/lib/agent/appengine-agent.jar, -Xbootclasspath/p:/Users/pm/Documents/GitHub/AppyBuilderPersonal/AppEngine/lib/override/appengine-dev-jdk-overrides.jar, -classpath, /Users/pm/Documents/GitHub/AppyBuilderPersonal/AppEngine/lib/appengine-tools-api.jar, com.google.appengine.tools.development.DevAppServerMain, --property=kickstart.user.dir=/Users/pm/Documents/GitHub/AppyBuilderPersonal, --port=8888, --address=0.0.0.0, /Users/pm/Documents/GitHub/AppyBuilderPersonal/GUIServer]
Feb 24, 2018 11:18:26 AM com.google.appengine.tools.admin.OutputPump run
SEVERE: Unexpected failure while trying to record errors.
java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:336)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at com.google.appengine.tools.admin.OutputPump.run(OutputPump.java:36)
	at java.base/java.lang.Thread.run(Thread.java:844)

Feb 24, 2018 11:18:26 AM com.google.appengine.tools.admin.OutputPump run
SEVERE: Unexpected failure while trying to record errors.
java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:336)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at com.google.appengine.tools.admin.OutputPump.run(OutputPump.java:36)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by PeterMathijssen** [comment]
AppyBuilder uses Java 8 to work.

**Comment by j2l** [comment]
You mean, it doesn't work with Java 9?

**Comment by PeterMathijssen** [comment]
No only with 8

2018-03-15 12:55 GMT+01:00 PM <notifications@github.com>:

**Comment by j2l** [comment]
Oh, ok.
I don't know how to downgrade Java and even if it's a good idea.
I'll  stick with Windows.
