### ISSUE TITLE
Termux : no such file or directory

### ISSUE THREAD

**Issue by ibnu-djamil** [AppyBuilder/AppyBuilderPersonal#9]
I don't have a PC, but I want to install appybuilder on Android termux, but I have problems when running startFrontend.sh

Exception in thread "main" java.lang.RuntimeException: Unable to start the process
        at com.google.appengine.tools.KickStart.<init>(KickStart.java:301)
        at com.google.appengine.tools.KickStart.main(KickStart.java:115)
Caused by: java.io.IOException: Cannot run program "/data/data/com.termux/files/usr/share/jdk8/jre/bin/java" (in directory "GUIServer"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.google.appengine.tools.KickStart.<init>(KickStart.java:299)
        ... 1 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 2 more
1|:/data/data/com.termux/files/home/AppyBuilderPersonal #

**Comment by Biangkerok32** [comment]
@ibnu-djamil you have fix?
you not just need jdk8 ,but more than..
try use install ubuntu on termux or other..
recomended use alphinelinux
